flight/PiOS/Common/pios_hal.c
flight/PiOS/inc/pios_hal.h
flight/targets/aq32/board-info/board_hw_defs.c
flight/targets/aq32/board-info/pios_board.h
flight/targets/aq32/fw/Makefile
flight/targets/aq32/fw/pios_board.c
flight/targets/naze32/fw/pios_board.c
flight/targets/pipxtreme/fw/pios_board.c
flight/targets/revomini/fw/pios_board.c
flight/targets/sparky2/fw/pios_board.c
shared/uavobjectdefinition/hwaq32.xml
shared/uavobjectdefinition/hwshared.xml

First cut at this.  Not fully functional, uart2 (configured for GPS) does not seem to work, but uart6 (configured for DSM) does.  Continuing to troubleshoot.  Scope of PR kind of grew when I had to add PWM RX support to PIOS_HAL.c

AQ32 - Reformat AQ32 target to use PIOS_HAL.

---

flight/Modules/UAVOMSPBridge/UAVOMSPBridge.c

This change creates a new MSP command that allows the peer (e.g. OSD) to ask for alarms from the flight controller. The alarm message includes severity and a message. In its current form, only one alarm is sent (fairly arbitrarily, other than severity taking precedence). Also, as a special and very useful case, boot reason is considered a warning from the perspective of the MSP code for the first few seconds. It might be worth generally considering that an alarm which would allow this special case code to be removed.
This has been very useful to me in showing both regular alarms (e.g. I let someone fly my sparky yesterday and saw 'MAN:NO RX' flashing on the screen because OpenTX companion turned off the radio for that profile) as well as boot reasons (saw watchdog firing in flight instead …

MSP Alarm Support

---

flight/PiOS/Common/pios_hal.c
flight/PiOS/inc/pios_hal.h
flight/targets/aq32/fw/pios_board.c
flight/targets/coptercontrol/fw/pios_board.c
flight/targets/naze32/fw/pios_board.c
flight/targets/pipxtreme/fw/pios_board.c
flight/targets/quanton/fw/pios_board.c
flight/targets/revomini/fw/pios_board.c
flight/targets/sparky/fw/pios_board.c
flight/targets/sparky2/fw/pios_board.c

Code builds correctly.  Have not tested it yet.  I can try running it on Sparky, Quanton, and AQ32, but most likely not until the weekend.
Figured we could at least start looking it over for the review.

F3frsky - Restore operation under PIOS_HAL

---

ground/gcs/gcs.pri
ground/gcs/src/libs/libcrashreporter-qt/breakpad/client/linux/handler/exception_handler.cc
ground/gcs/src/libs/libcrashreporter-qt/breakpad/common/linux/ignore_ret.h
ground/gcs/src/plugins/config/configosdwidget.cpp
ground/gcs/src/plugins/config/configoutputwidget.cpp
ground/gcs/src/plugins/config/expocurve.h

Fixes #84 
After this:
```
mike@mike-desktop:~/Dev/dronin$ make all_clean
[ ! -d "/home/mike/Dev/dronin/build" ] || rm -r "/home/mike/Dev/dronin/build"
mike@mike-desktop:~/Dev/dronin$ make -j8 gcs 1> /dev/null
Project MESSAGE: tlfw_resource.qrc not found.  Automatically firmware updates disabled.
```

GCS: Fix all of the compiler warnings

---

ground/gcs/src/plugins/uavobjectbrowser/treeitem.h
ground/gcs/src/plugins/uavobjectbrowser/uavobjecttreemodel.cpp
ground/gcs/src/plugins/uavobjects/uavobjectfield.cpp
ground/gcs/src/plugins/uavobjects/uavobjectfield.h
ground/gcs/src/plugins/uavobjects/uavobjecttemplate.cpp
ground/gcs/src/plugins/uavobjects/uavobjecttemplate.h
ground/uavobjgenerator/generators/gcs/uavobjectgeneratorgcs.cpp
ground/uavobjgenerator/generators/gcs/uavobjectgeneratorgcs.h
ground/uavobjgenerator/uavobjectparser.cpp
ground/uavobjgenerator/uavobjectparser.h
python/dronin/uavo.py
shared/uavobjectdefinition/actuatorsettings.xml
shared/uavobjectdefinition/attitudesettings.xml
shared/uavobjectdefinition/homelocation.xml
shared/uavobjectdefinition/taskinfo.xml

I was going to sleep but then I kept thinking about this :-P. Fixes #41.
UAVOs can now have an optional description element inside each field. This field is used in the GCS object browser to display tooltips on each UAVO field. No field descriptions are actually defined in this PR (an issue will be created once merged). To test you will need to add a description to one or more fields, e.g. in https://github.com/d-ronin/dronin/blob/next/shared/uavobjectdefinition/actuatorsettings.xml#L4:
```xml
<field name="TimerUpdateFreq" units="Hz" type="uint16" elements="6" defaultvalue="50">
<description>How often your spinny things get a fresh command.</description>
</field>
```

UAVO: Add description element to fields, add tooltips in UAVO Browser

---

Doxygen/ground_doxygen.cfg

I disabled this for flight, but missed it on ground. It was generating broken tex files thus was just cluttering the build dir with useless files.

Docs: Disable LaTeX output for ground

---

flight/targets/brain/fw/FreeRTOSConfig.h
flight/targets/brain/fw/chconf.h
flight/targets/flyingf3/fw/chconf.h

Not sure why FlyingF3 was missed; Brain was missed because it was not-yet-in-tree.

flight: disable stack checking on targets that were missed

---

ground/gcs/src/plugins/coreplugin/connectionmanager.cpp
ground/gcs/src/plugins/coreplugin/connectionmanager.h

If the attempted connection fails, we fail silently except for a message to the debug log, not super friendly to users who will see that nothing happened when they clicked connect. This adds a popup message box.

GCS:ConnectionMgr: Messagebox on connect failed

---

ground/gcs/src/libs/tlmapcontrol/internals/core.cpp

* Checked against sizeof(some ridiculous shit) which is uint.

Add an explicit uint bitsWithZoom

---

flight/targets/coptercontrol/fw/pios_board.c
flight/targets/sparky/fw/pios_board.c
shared/uavobjectdefinition/hwaq32.xml
shared/uavobjectdefinition/hwcoptercontrol.xml
shared/uavobjectdefinition/hwflyingf3.xml
shared/uavobjectdefinition/hwquanton.xml
shared/uavobjectdefinition/hwrevomini.xml
shared/uavobjectdefinition/hwsparky.xml

1) 444Hz never makes sense on Sparky, so remove it.  (it only works with
the DLPF disabled in which case you're guaranteed aliasing).
2) Set all 666Hz/DLPF disabled targets to 500Hz/188Hz by default--
except colibri.  We know enough about the platform being flown there to
know those defaults work out OK.
3) Change targets with gyrorange of 500 deg/s default to 1000deg/s.

flight: alterations to gyro settings.

---

ground/gcs/src/plugins/uavtalk/telemetrymonitor.cpp

[The empty() function just returns whether the queue is empty](http://doc.qt.io/qt-5/qlist.html#empty), this was not the intent of the code. I have tested this briefly to make sure I can still connect/disconnect/reconnect/flash firmware/reboot/etc. Seems to be great.

GCS:UAVTalk: Clear queues properly

---

ground/gcs/src/plugins/config/configattitudewidget.cpp

F1 boards don't have this object and it generates a warning when not present and the Attitude tab is saved.
Fixes #131.

GCS:Config: Ignore lack of StateEstimation object

---

ground/gcs/src/libs/libcrashreporter-qt/libcrashreporter-qt.pro

Stops QMake issuing a warning, still doesn't fix crash reporter on OSX (even with the other PR on top).

GCS:CrashReporter: Move objective-c sources into right place

---

flight/targets/naze32/fw/pios_board.c
shared/uavobjectdefinition/hwnaze.xml

This PR adds another receiver mode that enables only the serial port.
Testing:
All tests performed with RcvrSerial set to DSM.
1)RcvrPort set to PPM.  Connect PPM receiver.  PPM rx recognized, and after setup, operates correctly.  Disconnect PPM receiver and connect DSM satellite receiver.  DSM receiver not recognized.
2)RcvrPort set to PPM+Serial.  Connect PPM receiver.  PPM rx recognized, and after setup, operates correctly.  Disconnect PPM receiver and connect DSM satellite receiver.  DSM Satellite receiver recognized, and after setup operates correctly.
3)RcvrPort set to Serial.  Connect PPM receiver.  PPM receiver not recognized.  Disconnect PPM receiver and connect DSM satellite receiver.  DSM Satellite receiver recognized, and after setup operates correctly.
I did have some issues …

Naze32 - Implement serial only receiver port mode.

---

make/tools.mk
make/winx86/bash_profile

Current Qt version available for download is 5.5.1 which resides in a different directory than 5.5.0. This changes allows new development environment setups to work out of the box. I suggest also changing the wiki to link directly to a specific version, or even the desired .exe as there are a lot to choose from and only one is the correct one.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/d-ronin/dronin/153)

Build: Update default windows env bash_profile

---

flight/Modules/UAVOMSPBridge/UAVOMSPBridge.c

Also, give the port back to UAVTalk if the MSP module is disabled so the board doesn't get stuck in a bricked state where it can't be connected to GCS. Mostly useful on the Naze32.
This is some hacks I did in my local branch a while back. Haven't tested it since cherry-picking into dronin tree. Fixes #158.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/d-ronin/dronin/159)

UAVOMSPBridge: Detect 57600 baud UAVTalk packets

---

ground/gcs/src/plugins/welcome/welcomeplugin.cpp

One too many lines removed in #134, results in m_welcomeMode and not being cleaned up and a subsequent warning on exiting GCS.
`There are 1 objects left in the plugin manager pool:  (Welcome::WelcomeMode(0xe84e80))`
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/d-ronin/dronin/203)

GCS: Remove WelcomeMode object

---

flight/Modules/System/systemmod.c
flight/PiOS.posix/posix/pios_heap.c
flight/PiOS/Common/pios_heap.c
flight/PiOS/inc/pios_heap.h
shared/uavobjectdefinition/systemstats.xml

Also adds descriptions to SystemStats UAVO fields while I was in there.
Tested on Quanton.
To test:
Possible that the PIOS_SYSTEM_STACK_SIZE may need bumped on F1s.
Fixes #183
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/d-ronin/dronin/235)

Check remaining size on fast heap

---

ground/gcs/src/plugins/coreplugin/iboardtype.h
ground/gcs/src/plugins/setupwizard/vehicleconfigurationhelper.cpp

The USBInfo fix isn't my favourite work. There doesn't seem to be any way to init all the fields of a struct to a default value without doing so explicitly(and thus writing code that breaks every time the struct definition changes) with GCC & C++11?
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/d-ronin/dronin/247)

Unbreak release build

---

flight/Modules/Logging/logging.c
flight/PiOS/Common/pios_streamfs.c
flight/UAVObjects/uavobjectmanager.c
flight/targets/brain/board-info/board_hw_defs.c
ground/gcs/src/plugins/logging/flightlogdownload.cpp
shared/uavobjectdefinition/loggingsettings.xml
shared/uavobjectdefinition/loggingstats.xml

This is an improved version of https://github.com/TauLabs/TauLabs/pull/2031 Improvements:
- Configurable max logging frequency
- Logging profiles: The Default profile will just log a small subset of UAVOs (as we did previously) and the Custom profile will use the per UAVO logging period. This is useful for development to e.g. log a few UAVOs with high rates. If we add a nice way to the GCS to configure the rates, we can remove the profiles in the future.
- Modified the UAVO manager so that deregistering callbacks doesn't leak memory, i.e., the same memory can be reused for new callbacks
This WIP and has not yet been tested..
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/d-ronin/dronin/180)

Logging Module Improvements V3

---

ground/gcs/src/plugins/config/configautotunewidget.cpp
ground/gcs/src/plugins/config/configautotunewidget.h

Oops, mistake from AT sharing work. This was generating a warning about invalid signal, and not cleaning up properly.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/d-ronin/dronin/331)

GCS:Config: Fix broken signal in autotune share

---

flight/Modules/TxPID/txpid.c

This PR dynamically allocates memory for the large memory variables used in the code, preventing the stack from being depleted. Also fixes a problem where the Init function could try to construct a periodic callback before that system was running.
Tested on Sparky2 with TxPID on and off, also tested functionality of TxPID with FrSky S.PORT X4R-SB RX.
Fixes #370
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/d-ronin/dronin/374)

TxPID stack and Init fix

---

flight/Modules/Actuator/actuator.c
flight/PiOS/STM32F10x/pios_servo.c
flight/PiOS/STM32F30x/pios_servo.c
flight/PiOS/STM32F4xx/pios_servo.c
flight/PiOS/inc/pios_servo.h

Now max pulse length is passed into pios_servo, and we make sure we're
"past" that point by a defined margin before we'll disable the timer.
pios_servo should get factored common in the future and non-HPWM
variants of the code should get removed in that refactor.
This depends on all channels in a oneshot bank being defined with the
same "max" time to be fully protective.
Fixes #337
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/d-ronin/dronin/342)

pios_servo/oneshot: Ensure dead time.

---

flight/Modules/OnScreenDisplay/onscreendisplay.c

Fixes #429
Bench tested, works.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/d-ronin/dronin/432)

OSD: delay stats display by 1.5s

---

ground/gcs/src/libs/utils/mytabbedstackwidget.cpp

Should stop the scrollbar hiding the icons and labels when it is present. Tested on Linux, needs tested on Windows and OS X (OS might ignore it there I think).
Fixes #260 more.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/d-ronin/dronin/441)
Needs:

GCS:Config: Restyle widget scrollbar similar to OSX

---

ground/gcs/src/plugins/config/input.ui

Fixes #427 
Also changes default input tab to be RC input.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/d-ronin/dronin/446)

GCS:Config:Input: Add description of arming timeout

---

ground/gcs/src/plugins/config/configautotunewidget.cpp
ground/gcs/src/plugins/usagestatsgadget/usagestatsplugin.cpp

Use a cryptographic hash to obfuscate the chip serial number in the shared autotune results. 
The rationale for doing this is that the serial number may be used for other things, like warranty claims or registering the controller with a manufacturer, so the serial number should be kept private. While this is not 100% secure (it may be possible to guess a valid serial # due to limited entropy), this is IMO better than not obfuscating the number at all.
Compile but not tested. This should go into the Renatus release, otherwise we will not be able to associate boards with each other in the future.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/d-ronin/dronin/469)

GCS: Obfuscate chip serial # in AT results
