d-ronin/dRonin

- Doxygen/flight_doxygen.cfg
- Doxygen/ground_doxygen.cfg
- Makefile
- make/firmware-common.mk
Updated configs with doxygen -u, fixed paths
> Doxygen: Update configs, add to Makefile

- flight/Modules/Autotune/autotune.c
- shared/uavobjectdefinition/systemident.xml
Also prevent spamming the UAVO.
> autotune: add a prediction counter

- Makefile
- README.md
This is mostly here to play with PR building.  Jenkins isn't configured to do notification through github/doesn't have credentials yet.  But will it try to build?
> makefile: eliminate silliness

- README.md
> Update targets in README to include Brain

- ground/gcs/src/plugins/boards_brainfpv/brain.cpp
- ground/gcs/src/plugins/boards_brainfpv/brain.h
- ground/gcs/src/plugins/boards_brainfpv/brainconfiguration.cpp
Part of the Brain plugin was coming up under the Tau Labs plugin.
> GCS:Brain: Fix doxygen grouping

- ground/gcs/src/plugins/rawhid/rawhid.cpp
> GCS:RawHID: Fix open() bug that caused segfaults

- flight/Modules/OnScreenDisplay/onscreendisplay.c
I haven't tested this because I don't yet have a Brain but this fixes the build.
Fixes #78
> OSD: Fix UAVO event callback usage

- ground/gcs/src/plugins/config/configgadget.qrc
- ground/gcs/src/plugins/config/configgadgetwidget.cpp
- ground/gcs/src/plugins/config/configgadgetwidget.h
Add OSD configuration to GCS. This was somehow missed in #36
> FIX: Add OSD config to GCS

- ground/gcs/src/plugins/config/configmodulewidget.cpp
> GCS:Config: Plumb logging module checkbox

- ground/gcs/src/plugins/uavobjectutil/uavobjectutilmanager.cpp
> GCS: Change release tags to Release-yyyymmdd

- ground/gcs/src/plugins/pfdqml/pfdqmlgadget.cpp
- ground/gcs/src/plugins/welcome/welcomeplugin.cpp
See TauLabs/TauLabs#2101. Really nice work by @PTDreamer.
Fixes #121 
I confirmed that it does fix the scenario reported in #121.
> GCS: Fix racing condition which leads to a segfault on exit

- flight/Libraries/alarms.c
- flight/Libraries/inc/alarms.h
- flight/Modules/OnScreenDisplay/onscreendisplay.c
- flight/Modules/UAVOMSPBridge/UAVOMSPBridge.c
This currently moves the MSP variant of string (and boot)
stringification into a common location.  The intention is to share the
code with BrainFPV and MSP (and anyone else who wants to string an
alarm).
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/d-ronin/dronin/63)
> Refactor alarm stringing for reuse.

- flight/targets/discoveryf4/fw/Makefile
- flight/targets/discoveryf4/fw/board.c
- flight/targets/discoveryf4/fw/board.h
- flight/targets/discoveryf4/fw/chconf.h
- flight/targets/discoveryf4/fw/halconf.h
- flight/targets/discoveryf4/fw/main.c
- flight/targets/discoveryf4/fw/mcuconf.h
- flight/targets/discoveryf4/fw/memory.ld
- flight/targets/discoveryf4/fw/pios_config.h
It boots and connects to GCS.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/d-ronin/dronin/179)
> DiscoF4: Upgrade to ChibiOS

- ground/gcs/src/plugins/welcome/qml/SitesPanel.qml
Added links for facebook, twitter and instagram. Maybe @varcht can do something fancier
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/d-ronin/dronin/234)
> Add social media sites to community panel

- ground/gcs/src/plugins/boards_brainfpv/brain.h
Fixes #230
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/d-ronin/dronin/239)
> Brain: remove reference to nonexisting connection diagram

- LICENSE.txt
as per issue #213 
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/d-ronin/dronin/240)
> cleanup LICENSE.txt

- ground/gcs/src/plugins/coreplugin/iboardtype.h
- ground/gcs/src/plugins/setupwizard/vehicleconfigurationhelper.cpp
Reverts d-ronin/dRonin#247
Per @tracernz, superseded by #253
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/d-ronin/dronin/258)
> Revert "Unbreak release build"

- ground/gcs/share/welcome/SitesPanel.qml
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/d-ronin/dronin/270)
> GCS: Fix github links

- flight/Modules/OnScreenDisplay/osd_menu.c
Tested on brain using the OSD menu with some ridiculous PID values.
Fixes #194
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/d-ronin/dronin/276)
> FIX: Remove PID limits in OSD menu

- flight/Modules/Stabilization/stabilization.c
Fix maximum yaw_scale to match the tested value
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/d-ronin/dronin/262)
> Fix maximum yaw_scale to match the tested value

- flight/Modules/CameraStab/camerastab.c
- flight/Modules/Geofence/geofence.c
Fixes #375
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/d-ronin/dronin/376)
> Separated module init and start steps to ensure proper operation

- shared/uavobjectdefinition/actuatorsettings.xml
This reverts commit 3f94d9ae6020b5341164e8c4f58be9886e20e345 
Fixes #386
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/d-ronin/dronin/387)
> Revert "actuatorsettings: default to 400Hz PWM."

- ground/gcs/src/plugins/coreplugin/dialogs/importsettings.ui
- ground/gcs/src/plugins/usagestatsgadget/usagestatsplugin.cpp
Tested on Linux. 
Fixes #470
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/d-ronin/dronin/475)
> GCS Usage Stats: Notify user, save config
